List of [[Hercules Original|Original Hercules Features]]
* <span style="color:red;">'''[New]'''</span>[http://herc.ws/board/topic/2954-item-db-file-structure-overhaul/ Item DB File Structure Overhaul]
* [http://herc.ws/board/topic/302-introducing-hercules-map-zone-database/ Hercules Map Zone DB]
* [[HPM|Hercules Plugin Mananger]]
* [http://herc.ws/board/topic/316-introducing-hercules-channel-system/ Hercules Channel System]
* [http://herc.ws/board/topic/353-packetdb-overhaul/ Packet DB Overhaul]
* [http://herc.ws/board/topic/548-hercules-console-input-update/ Console Input Redesign]
[[Category:Hercules]]